# Generated by Django 4.1.1 on 2022-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=2)),
            ],
        ),
    ]
